name: e2e-complex
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for API response
        run: |
          touch test.sh
          chmod +x test.sh
          echo "#!/bin/bash" >> test.sh
          echo "url=https://api-biohubbc.apps.silver.devops.gov.bc.ca/version" >> test.sh
          cat test.sh
