name: e2e-complex
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for API response
        uses: nev7n/wait_for_response@v1.0.1
        with:
          url: https://api-biohubbc.apps.silver.devops.gov.bc.ca/version
          responseCode: 200
          timeout: 240000
          interval: 500

      - name: Wait for API response
        run: |
          bash url=https://api-biohubbc.apps.silver.devops.gov.bc.ca/version
          > code=200
          > wait_time=240000
          > max_attempts=3
          > attempt_counter: 0
          > until [ $(curl --output /dev/null --silent --head -X GET --retry 5 --fail --retry-delay 5 -w "%{response_code}\n" ${url}) -eq ${code} ]; do
          >     if [ ${attempt_counter} -eq ${max_attempts} ];then
          >       echo "Failed Connection"
          >       exit 1
          >     fi
          >     printf '.'
          >     attempt_counter=$(($attempt_counter+1))
          >     sleep $wait_time
          > done
